### ISSUE TITLE
ヒアドキュメント実行中にsignalを受け取ったときの挙動を実装

### ISSUE THREAD

**Issue by kiri-42** [42Student-July/minishell#75]
## 機能の目的
ヒアドキュメント実行中にsignalを受け取ったときのbashの挙動を再現する

**Comment by AkkyOrz** [comment]
シグナルを受け取ったあと、readlineをプログラム側から正常に終了させる方法がない。
よって、子プロセスを作成し、子プロセス上でreadlineを行い、シグナルを受け取ったらexitすることでreadlineを終了させる予定

**Comment by AkkyOrz** [comment]
ただし、親プロセス側はsignalを受け取ってもignoreする必要が有ることに注意
